---

# This playbook creates a Hello world file on target host

- hosts: node1
  gather_facts: yes
  become: true
  tasks:
    - name: Hello world file
      ansible.builtin.file:
        state: touch
        path: /home/ec2-user/hello.txt
        owner: ec2-user
        group: ec2-user
        mode: "u=rw,g=r,o=r"

    - name: Adding greeting to file
      ansible.builtin.lineinfile:
        path: /home/ec2-user/hello.txt
        line: "Hello world!"
